### ISSUE TITLE
Incorrect type for `MasterDokiThemeDefinition`

### ISSUE THREAD

**Issue by nopeless** [doki-theme/doki-theme-template#2]
`<MasterDokiThemeDefinition>.stickers.default` is annotated to be a `string` but is actually 
```ts
interface {
name: string,
anchor: string,
opacity: number
}
```

Can you please fix this type annotation

**Comment by Unthrottled** [comment]
The fix is bumping the build source to the most current version, will update & push the changes 

https://github.com/doki-theme/doki-build-source/blob/95478dbb7d9c614b2a833f66f9bebacf7625df9f/src/types.ts#L13
